import type { TriggerListItem } from '../interfaces';

/**
 * Unified triggers list stub data
 * Contains both technical and communication triggers
 */
export const UNIFIED_TRIGGERS_LIST_STUB: TriggerListItem[] = [
  // Technical Triggers (📡)
  {
    id: 'trigger-http-001',
    name: 'Production Alert HTTP',
    description: 'Send alerts to production monitoring system via HTTP',
    triggerType: 'http',
    category: 'technical',
    status: 'Active',
    icon: 'mdi-web',
    createdAt: '2024-03-15T10:30:00',
    updatedAt: '2024-03-15T10:30:00',
  },
  {
    id: 'trigger-mqtt-001',
    name: 'Device Status MQTT',
    description: 'Publish device status updates to MQTT broker',
    triggerType: 'mqtt',
    category: 'technical',
    status: 'Active',
    icon: 'mdi-transit-connection-variant',
    createdAt: '2024-03-14T14:20:00',
    updatedAt: '2024-03-14T14:20:00',
  },
  {
    id: 'trigger-rabbitmq-001',
    name: 'Event Queue Publisher',
    description: 'Send events to RabbitMQ processing queue',
    triggerType: 'rabbitmq',
    category: 'technical',
    status: 'Active',
    icon: 'mdi-rabbit',
    createdAt: '2024-03-13T09:15:00',
    updatedAt: '2024-03-13T09:15:00',
  },
  {
    id: 'trigger-websocket-001',
    name: 'Real-time Dashboard Updates',
    description: 'Push real-time updates to connected WebSocket clients',
    triggerType: 'websocket',
    category: 'technical',
    status: 'Active',
    icon: 'mdi-swap-horizontal',
    createdAt: '2024-03-12T16:45:00',
    updatedAt: '2024-03-12T16:45:00',
  },

  // Communication Triggers (💬)
  {
    id: 'trigger-email-001',
    name: 'Critical Alert Email',
    description: 'Send critical alerts to operations team via email',
    triggerType: 'email',
    category: 'communication',
    status: 'Active',
    icon: 'mdi-email',
    createdAt: '2024-03-15T11:00:00',
    updatedAt: '2024-03-15T11:00:00',
  },
  {
    id: 'trigger-slack-001',
    name: 'DevOps Team Slack',
    description: 'Post notifications to #devops-alerts Slack channel',
    triggerType: 'slack',
    category: 'communication',
    status: 'Active',
    icon: 'mdi-slack',
    createdAt: '2024-03-14T13:30:00',
    updatedAt: '2024-03-14T13:30:00',
  },
  {
    id: 'trigger-teams-001',
    name: 'Management Teams Notification',
    description: 'Send updates to management team via Microsoft Teams',
    triggerType: 'teams',
    category: 'communication',
    status: 'Active',
    icon: 'mdi-microsoft-teams',
    createdAt: '2024-03-13T10:00:00',
    updatedAt: '2024-03-13T10:00:00',
  },
  {
    id: 'trigger-push-001',
    name: 'Mobile App Push Notifications',
    description: 'Send push notifications to mobile app users',
    triggerType: 'push',
    category: 'communication',
    status: 'Active',
    icon: 'mdi-bell-ring',
    createdAt: '2024-03-11T15:20:00',
    updatedAt: '2024-03-11T15:20:00',
  },
  {
    id: 'trigger-sms-001',
    name: 'Emergency SMS Alerts',
    description: 'Send SMS alerts to on-call personnel',
    triggerType: 'sms',
    category: 'communication',
    status: 'Active',
    icon: 'mdi-message-text',
    createdAt: '2024-03-10T08:45:00',
    updatedAt: '2024-03-10T08:45:00',
  },

  // Inactive Triggers
  {
    id: 'trigger-email-002',
    name: 'Weekly Report Email',
    description: 'Send weekly summary reports (currently disabled)',
    triggerType: 'email',
    category: 'communication',
    status: 'Inactive',
    icon: 'mdi-email',
    createdAt: '2024-02-20T12:00:00',
    updatedAt: '2024-03-01T09:30:00',
  },
  {
    id: 'trigger-tcp-001',
    name: 'Legacy TCP Notification',
    description: 'TCP socket notification (deprecated)',
    triggerType: 'tcp',
    category: 'technical',
    status: 'Inactive',
    icon: 'mdi-lan',
    createdAt: '2024-01-15T10:00:00',
    updatedAt: '2024-02-28T14:20:00',
  },
];
