export const ASSET_LIST_STUB = [
	{
		id: '1',
		name: 'Temperature Sensor A1',
		description: 'Measures ambient temperature in warehouse zone A',
		icon: 'thermostat',
		status: true,
		assetUUID: 'temp-sensor-001-uuid',
		assetType: 'sensor',
		assetTypeName: 'Temperature Sensor',
		category: 'environmental',
		categoryName: 'Environmental Monitoring',
		protocol: {
			type: 'mqtt' as const,
			mqtt: {
				clientId: 'temp-sensor-001',
				username: 'sensor_user',
				password: '********',
			},
		},
		created: '2024-03-15T10:30:00',
		updated: '2024-03-15T10:30:00',
	},
	{
		id: '2',
		name: 'Humidity Sensor B2',
		description: 'Monitors humidity levels in storage room',
		icon: 'water_drop',
		status: true,
		assetUUID: 'humidity-sensor-002-uuid',
		assetType: 'sensor',
		assetTypeName: 'Humidity Sensor',
		category: 'environmental',
		categoryName: 'Environmental Monitoring',
		protocol: {
			type: 'mqtt' as const,
			mqtt: {
				clientId: 'humidity-sensor-002',
				username: 'sensor_user',
				password: '********',
			},
		},
		created: '2024-03-14T09:20:00',
		updated: '2024-03-15T11:45:00',
	},
	{
		id: '3',
		name: 'Gateway Edge-01',
		description: 'Main IoT gateway for building floor 1',
		icon: 'router',
		status: true,
		assetUUID: 'gateway-edge-01-uuid',
		assetType: 'gateway',
		assetTypeName: 'LoRaWAN Gateway',
		category: 'network',
		categoryName: 'Network Infrastructure',
		protocol: {
			type: 'lorawan' as const,
		},
		latitude: -23.550520,
		longitude: -46.633308,
		created: '2024-02-10T08:00:00',
		updated: '2024-03-15T10:30:00',
	},
	{
		id: '4',
		name: 'Motion Detector C3',
		description: 'PIR motion sensor for security monitoring',
		icon: 'sensors',
		status: false,
		assetUUID: 'motion-detector-003-uuid',
		assetType: 'sensor',
		assetTypeName: 'Motion Sensor',
		category: 'security',
		categoryName: 'Security Systems',
		protocol: {
			type: 'http' as const,
			http: {
				endpoint: 'https://api.example.com/motion',
				method: 'POST',
			},
		},
		created: '2024-03-10T14:20:00',
		updated: '2024-03-12T16:00:00',
	},
	{
		id: '5',
		name: 'Energy Meter D4',
		description: 'Smart energy consumption meter',
		icon: 'electric_meter',
		status: true,
		assetUUID: 'energy-meter-004-uuid',
		assetType: 'meter',
		assetTypeName: 'Energy Meter',
		category: 'utilities',
		categoryName: 'Utility Management',
		protocol: {
			type: 'mqtt' as const,
			mqtt: {
				clientId: 'energy-meter-004',
				username: 'meter_user',
				password: '********',
			},
		},
		created: '2024-01-20T12:00:00',
		updated: '2024-03-15T09:15:00',
	},
	{
		id: '6',
		name: 'Pressure Sensor E5',
		description: 'Industrial pressure monitoring sensor',
		icon: 'compress',
		status: true,
		assetUUID: 'pressure-sensor-005-uuid',
		assetType: 'sensor',
		assetTypeName: 'Pressure Sensor',
		category: 'industrial',
		categoryName: 'Industrial Equipment',
		protocol: {
			type: 'http' as const,
			http: {
				endpoint: 'https://api.example.com/pressure',
				method: 'POST',
			},
		},
		created: '2024-03-01T10:30:00',
		updated: '2024-03-14T13:20:00',
	},
];