/**
 * Message types for script processing.
 * Data transfer objects received from NATS consumers (interface layer)
 * and consumed by application services.
 */

export type AssetBindType = 'fixedAssetId' | 'uuidField' | 'dynamicAssetId';

/**
 * Source type indicates the origin gateway of the event.
 * Used to determine how to resolve the assetUUID.
 *
 * - 'http': HTTP DataSource gateway - requires assetBind to resolve assetUUID
 * - 'mqtt': MQTT gateway - the deviceId IS the assetUUID
 * - 'lorawan': LoRaWAN network server (TTN/ChirpStack) - the devEUI IS the assetUUID
 */
export type SourceType = 'http' | 'mqtt' | 'lorawan';

/**
 * Bind type to association
 */
interface AssetBind {
	type: AssetBindType;
	data: {
		uuidField?: string[];
		assetId?: string | null;
	};
}

/**
 * Data source configuration.
 * Note: assetBind is optional - only required for HTTP gateway.
 */
export interface DataSource {
	id?: string;
	name?: string;
	enabled?: boolean;
	description?: string | null;
	/** Optional for MQTT/LoRaWAN - required for HTTP */
	assetBind?: AssetBind;
	/** Organization ID for multi-tenant filtering */
	orgId?: string;
	/** Hierarchical path for multi-tenant range queries */
	pathKey?: string;
}

/**
 * Represents the message payload received from NATS.
 * Data transfer object for external communication.
 */
export interface ScriptProcessorMessage {
	/** Source type indicates the origin gateway (http, mqtt, lorawan) */
	sourceType: SourceType;
	/** The data source configuration */
	dataSource: DataSource;
	/** The payload data to process through the scripts */
	event: any;
	/**
	 * Asset UUID - pre-resolved for MQTT/LoRaWAN sources
	 * For HTTP sources, this is resolved using assetBind configuration
	 */
	assetUUID?: string;
	/**
	 * Event Tracker ID - UUID generated by JS-Executor for end-to-end event tracking.
	 * This ID is propagated through all services: JS-Executor → Router → Rule Engine → Triggers
	 * and stored in ClickHouse for correlation and tracing.
	 */
	eventTrackerId?: string;
}

/**
 * LorawanUplinkEnvelope is the wire contract js-executor expects on
 * ${env}.mapexos.lorawan.data.> — published by the mapexLNS adapter (the
 * Anti-Corruption Layer over The Things Stack). Mirrors the broker's
 * IngressMessage style: every routing field travels in the JSON body, the
 * subject stays agnostic.
 *
 * `orgId` and `assetUUID` are required (handler rejects otherwise). `payload`
 * is the raw FRMPayload, base64-encoded (Go marshals []byte as base64). The
 * LoRaWAN-standard fields (fPort, fCnt, rxInfo) ride alongside so the device
 * codec can decode the bytes in the decode step.
 */
export interface LorawanUplinkEnvelope {
	/** Organization ID (TTS application_id) */
	orgId: string;
	/** Asset UUID (TTS device_id / devEUI) */
	assetUUID: string;
	/** Raw FRMPayload, base64-encoded */
	payload?: string;
	/** LoRaWAN frame port */
	fPort?: number;
	/** LoRaWAN frame counter */
	fCnt?: number;
	/** Gateway rx metadata (RSSI, SNR, timestamps, ...) */
	rxInfo?: unknown;
	/** Uplink reception time (RFC3339), for parity with the broker envelope */
	timestamp?: string;
}

/**
 * LorawanDecodeInput is what the device codec sees as the global `payload` in
 * the decode step: the FRMPayload as a byte array plus the frame metadata.
 * Shaped after the TTN/ChirpStack codec convention
 * (decodeUplink({ bytes, fPort })).
 */
export interface LorawanDecodeInput {
	/** Decoded FRMPayload bytes */
	bytes: number[];
	/** LoRaWAN frame port */
	fPort: number;
	/** LoRaWAN frame counter */
	fCnt: number;
	/** Gateway rx metadata */
	rxInfo?: unknown;
}

/**
 * Represents the message payload received from NATS for script updates.
 */
export interface ScriptUpdateMessage {
	/** The ID of the asset to fetch the new scripts for */
	assetId: string;
}
