/**
 * Message types for script processing.
 * Data transfer objects received from NATS consumers (interface layer)
 * and consumed by application services.
 */

export type AssetBindType = 'fixedAssetId' | 'uuidField' | 'dynamicAssetId';

/**
 * Source type indicates the origin gateway of the event.
 * Used to determine how to resolve the assetUUID.
 *
 * - 'http': HTTP DataSource gateway - requires assetBind to resolve assetUUID
 * - 'mqtt': MQTT gateway - the deviceId IS the assetUUID
 * - 'lorawan': LoRaWAN network server (TTN/ChirpStack) - the devEUI IS the assetUUID
 */
export type SourceType = 'http' | 'mqtt' | 'lorawan';

/**
 * Bind type to association
 */
interface AssetBind {
	type: AssetBindType;
	data: {
		uuidField?: string[];
		assetId?: string | null;
	};
}

/**
 * Data source configuration.
 * Note: assetBind is optional - only required for HTTP gateway.
 */
export interface DataSource {
	id?: string;
	name?: string;
	enabled?: boolean;
	description?: string | null;
	/** Optional for MQTT/LoRaWAN - required for HTTP */
	assetBind?: AssetBind;
	/** Organization ID for multi-tenant filtering */
	orgId?: string;
	/** Hierarchical path for multi-tenant range queries */
	pathKey?: string;
}

/**
 * Represents the message payload received from NATS.
 * Data transfer object for external communication.
 */
export interface ScriptProcessorMessage {
	/** Source type indicates the origin gateway (http, mqtt, lorawan) */
	sourceType: SourceType;
	/** The data source configuration */
	dataSource: DataSource;
	/** The payload data to process through the scripts */
	event: any;
	/**
	 * Asset UUID - pre-resolved for MQTT/LoRaWAN sources
	 * For HTTP sources, this is resolved using assetBind configuration
	 */
	assetUUID?: string;
	/**
	 * Event Tracker ID - UUID generated by JS-Executor for end-to-end event tracking.
	 * This ID is propagated through all services: JS-Executor → Router → Rule Engine → Triggers
	 * and stored in ClickHouse for correlation and tracing.
	 */
	eventTrackerId?: string;
}

/**
 * Represents the message payload received from NATS for script updates.
 */
export interface ScriptUpdateMessage {
	/** The ID of the asset to fetch the new scripts for */
	assetId: string;
}
