package entities

import (
	"time"

	model "github.com/Mapex-Solutions/mapexGoKit/infrastructure/mongodb/model"
)

// ExecutionStatus represents the lifecycle state of a workflow execution.
type ExecutionStatus string

const (
	// ExecStatusCreated indicates the execution was created but has not started.
	ExecStatusCreated ExecutionStatus = "created"
	// ExecStatusRunning indicates the execution is actively traversing nodes.
	ExecStatusRunning ExecutionStatus = "running"
	// ExecStatusWaiting indicates the execution is suspended on an async node.
	ExecStatusWaiting ExecutionStatus = "waiting"
	// ExecStatusCompleted indicates the execution finished all nodes successfully.
	ExecStatusCompleted ExecutionStatus = "completed"
	// ExecStatusFailed indicates the execution encountered an unrecoverable error.
	ExecStatusFailed ExecutionStatus = "failed"
	// ExecStatusCancelled indicates the execution was manually cancelled.
	ExecStatusCancelled ExecutionStatus = "cancelled"
)

// IsTerminal returns true if the status is a terminal state (completed, failed, or cancelled).
func (s ExecutionStatus) IsTerminal() bool {
	return s == ExecStatusCompleted || s == ExecStatusFailed || s == ExecStatusCancelled
}

// WorkflowExecution is the root aggregate for a single run of a WorkflowInstance.
// Hot state lives in NATS KV during execution (key: exec:{uuid}).
// The Archiver persists terminal states to MongoDB (collection: executions).
// One instance can produce N executions (1:N relationship).
type WorkflowExecution struct {
	// ID is the MongoDB ObjectId — auto-generated by MongoDB.
	ID           model.ObjectId `bson:"_id,omitempty"`
	// WorkflowUUID is the execution identifier — user-provided or auto-generated GUIDv4.
	// Used as NATS KV key (exec.{id}) and unique index.
	WorkflowUUID string         `bson:"workflowUUID"`
	InstanceID   model.ObjectId `bson:"instanceId"`

	// Denormalized fields — set once at creation, never change.
	DefinitionID     model.ObjectId  `bson:"definitionId"`
	DefinitionName   string          `bson:"definitionName"`
	InstanceName     string          `bson:"instanceName"`
	WorkflowName     string          `bson:"workflowName"` // Legacy — kept for backward compatibility, same as InstanceName
	OrgID            *model.ObjectId `bson:"orgId"`
	PathKey        string          `bson:"pathKey"`                  // Hierarchical org path for multi-tenant queries
	EventTrackerId string          `bson:"eventTrackerId,omitempty"` // End-to-end tracking UUID from Router
	TriggerSource  string          `bson:"triggerSource"`            // Always "workflow"

	// Execution state — mutable, updated per-step in NATS KV.
	Version       int                                `bson:"version"`
	Status        ExecutionStatus                    `bson:"status"`
	ActiveNodeIDs []string                           `bson:"activeNodeIds"`
	NodeStates    map[string]map[string]interface{}   `bson:"nodeStates"`
	State          map[string]interface{}              `bson:"state"`
	ExternalInputs map[string]interface{}              `bson:"externalInputs"`
	ExecutionPath  []PathEntry                        `bson:"executionPath"`
	NodeOutputs    map[string]interface{}              `bson:"nodeOutputs"`
	ErrorInfo     *ExecutionError                    `bson:"errorInfo"`
	EventPayload  map[string]interface{}              `bson:"eventPayload"`

	// Subworkflow context.
	ParentExecutionID    *string `bson:"parentExecutionId"`
	ParentNodeID         string  `bson:"parentNodeId"`
	Depth                int     `bson:"depth"`
	CallbackSubject      string  `bson:"callbackSubject,omitempty"`      // NATS subject to resume parent on terminal state
	ParentExecutionToken string  `bson:"parentExecutionToken,omitempty"` // Parent's execution token for callback validation

	// Retention — carried from instance at creation, used by Archiver when publishing to ClickHouse.
	RetentionDays uint16 `bson:"retentionDays"` // 0 = use org policy

	// TTL — set on terminal state, MongoDB auto-deletes after expiration.
	ExpireAt *time.Time `bson:"expireAt,omitempty"`

	// Timestamps.
	StartedAt   *time.Time `bson:"startedAt"`
	CompletedAt *time.Time `bson:"completedAt"`
	Created     time.Time  `bson:"created"`
	Updated     time.Time  `bson:"updated"`
}

// GetCreated returns the creation timestamp.
func (e *WorkflowExecution) GetCreated() time.Time { return e.Created }

// GetUpdated returns the last update timestamp.
func (e *WorkflowExecution) GetUpdated() time.Time { return e.Updated }
