package dtos

import (
	"time"

	"github.com/Mapex-Solutions/MapexOS/contracts/common/query"
)

// Events Raw DTOs

// EventsRawQuery represents query parameters for listing raw events.
// Uses cursor-based pagination for efficient querying of large datasets.
//
// Standard fields (from CursorQueryDTO):
//   - Cursor: timestamp to start from (RFC3339 format)
//   - Direction: "next" (older items) or "prev" (newer items)
//   - Limit: max items to return (default: 20, max: 100)
//   - SortAsc: false = DESC (newest first), true = ASC (oldest first)
//   - IncludeChildren: include child orgs hierarchically (default: false)
//
// Module-specific filters:
//   - ThreadId: filter by thread ID (data source identifier)
//   - Source: filter by source (http_gateway, mqtt_gateway, etc.)
//   - StartTime: filter events after this timestamp
//   - EndTime: filter events before this timestamp
//
// Organization filtering is handled automatically via RequestContext:
//   - No manual customerId/pathKey needed
//   - Context-aware filtering via X-Org-Context header
//   - Hierarchical queries via includeChildren parameter
//
// Why cursor pagination?
//   - Raw events can have millions of records
//   - Offset pagination requires COUNT which is expensive on large tables
//   - Cursor pagination uses timestamp index directly (fast seeks)
type EventsRawQuery struct {
	query.CursorQueryDTO

	// Module-specific filters
	EventTrackerId *string    `query:"eventTrackerId" validate:"omitempty"`
	ThreadId       *string    `query:"threadId" validate:"omitempty"`
	Source         *string    `query:"source" validate:"omitempty"`
	Success        *bool      `query:"success" validate:"omitempty"`
	StartTime      *time.Time `query:"startTime" validate:"omitempty"`
	EndTime        *time.Time `query:"endTime" validate:"omitempty"`
}

// EventsRawResponse represents a raw event response.
type EventsRawResponse struct {
	Created        time.Time              `json:"created"`
	EventTrackerId string                 `json:"eventTrackerId,omitempty"`
	ThreadId       string                 `json:"threadId"`
	OrgId          string                 `json:"orgId"`
	Source         string                 `json:"source"`
	Name           string                 `json:"name,omitempty"`
	Description    string                 `json:"description,omitempty"`
	Event          map[string]interface{} `json:"event"`
	Metadata       map[string]interface{} `json:"metadata,omitempty"`
	Success        bool                   `json:"success"`
	Error          string                 `json:"error,omitempty"`
	RetentionDays  uint16                 `json:"retentionDays"`
}

// EventsRawCursorResult represents the cursor-paginated response for raw events.
type EventsRawCursorResult struct {
	// Items contains the list of raw events
	Items []EventsRawResponse `json:"items"`

	// NextCursor is the timestamp to use for fetching the next page
	// Empty if no more items in this direction
	NextCursor *time.Time `json:"nextCursor,omitempty"`

	// PrevCursor is the timestamp to use for fetching the previous page
	// Empty if at the beginning
	PrevCursor *time.Time `json:"prevCursor,omitempty"`

	// HasNext indicates if there are more items after the current page
	HasNext bool `json:"hasNext"`

	// HasPrevious indicates if there are more items before the current page
	HasPrevious bool `json:"hasPrevious"`
}

// RawEventDTO represents the payload received from gateways via NATS.
// This DTO is used by HTTP Gateway, MQTT Gateway, and other event sources.
//
// Required fields:
//   - ThreadId: Identifier for the data source (DataSource ID)
//   - OrgId: Organization ID for multi-tenant filtering
//   - PathKey: Hierarchical path for org-based queries
//   - Event: The actual event payload from the device/gateway
//   - Source: Gateway identifier (http_gateway, mqtt_gateway, lorawan_gateway)
//
// Optional fields:
//   - Created: Event timestamp (defaults to current time if not provided)
//   - Name: Friendly name for the data source (optional)
//   - Description: Description of the data source (optional)
//   - Success: Whether the gateway auth/validation succeeded (default: true)
//   - Error: Error message if Success is false (optional)
//   - EventTrackerId: UUID for tracking event across the pipeline (optional, generated by JS-Executor)
type RawEventDTO struct {
	// EventTrackerId is the UUID for tracking event across the pipeline (optional)
	EventTrackerId string `json:"eventTrackerId" validate:"omitempty"`

	// ThreadId is the data source identifier (required)
	ThreadId string `json:"threadId" validate:"required"`

	// OrgId is the organization ID for multi-tenant isolation (required)
	OrgId string `json:"orgId" validate:"required"`

	// PathKey is the hierarchical path for org-based filtering (required)
	PathKey string `json:"pathKey" validate:"required"`

	// Event is the actual payload from the gateway (required)
	Event map[string]interface{} `json:"event" validate:"required"`

	// Source identifies the originating gateway (http_gateway, mqtt_gateway, lorawan_gateway)
	Source string `json:"source" validate:"required"`

	// Created is the event occurrence time (optional, defaults to now)
	Created *time.Time `json:"created" validate:"omitempty"`

	// Name is a friendly name for the data source (optional)
	Name string `json:"name" validate:"omitempty"`

	// Description is a description of the data source (optional)
	Description string `json:"description" validate:"omitempty"`

	// Success indicates if gateway auth/validation succeeded (default: true)
	Success bool `json:"success"`

	// Error contains the error message if Success is false (optional)
	Error string `json:"error" validate:"omitempty"`
}
