package dtos

import (
	"time"

	"github.com/Mapex-Solutions/MapexOS/contracts/common/query"
)

/**
 * Events JsExecutor DTOs
 * Standardized field names matching events_raw pattern
 */

// ExecTimeOperator defines the comparison operator for execution time filtering.
// Valid values: "lt" (<), "lte" (<=), "gt" (>), "gte" (>=), "between"
type ExecTimeOperator string

const (
	ExecTimeOpLt      ExecTimeOperator = "lt"      // Less than
	ExecTimeOpLte     ExecTimeOperator = "lte"     // Less than or equal
	ExecTimeOpGt      ExecTimeOperator = "gt"      // Greater than
	ExecTimeOpGte     ExecTimeOperator = "gte"     // Greater than or equal
	ExecTimeOpBetween ExecTimeOperator = "between" // Between two values (inclusive)
)

// EventsJsExecQuery represents query parameters for listing JS Executor events.
// Uses cursor-based pagination for efficient querying of large datasets.
//
// Standard fields (from CursorQueryDTO):
//   - Cursor: timestamp to start from (RFC3339 format)
//   - Direction: "next" (older items) or "prev" (newer items)
//   - Limit: max items to return (default: 20, max: 100)
//   - SortAsc: false = DESC (newest first), true = ASC (oldest first)
//   - IncludeChildren: include child orgs hierarchically (default: false)
//
// Module-specific filters:
//   - ThreadId: filter by thread ID (asset UUID)
//   - Success: filter by execution success status
//   - StartTime: filter events after this timestamp
//   - EndTime: filter events before this timestamp
//   - ExecTimeOp: operator for execution time filter (lt, lte, gt, gte, between)
//   - ExecTimeValue: execution time value in milliseconds
//   - ExecTimeValueEnd: end value for "between" operator (milliseconds)
type EventsJsExecQuery struct {
	query.CursorQueryDTO

	// Module-specific filters
	EventTrackerId *string    `query:"eventTrackerId" validate:"omitempty"`
	ThreadId       *string    `query:"threadId" validate:"omitempty"`
	Success        *bool      `query:"success" validate:"omitempty"`
	StartTime      *time.Time `query:"startTime" validate:"omitempty"`
	EndTime        *time.Time `query:"endTime" validate:"omitempty"`

	// Execution time filter (in milliseconds)
	// ExecTimeOp: comparison operator (lt, lte, gt, gte, between)
	// ExecTimeValue: value to compare against
	// ExecTimeValueEnd: end value for "between" operator (required when ExecTimeOp is "between")
	ExecTimeOp       *ExecTimeOperator `query:"execTimeOp" validate:"omitempty,oneof=lt lte gt gte between"`
	ExecTimeValue    *uint32           `query:"execTimeValue" validate:"omitempty"`
	ExecTimeValueEnd *uint32           `query:"execTimeValueEnd" validate:"omitempty"`
}

// EventsJsExecResponse represents a JS Executor event response.
type EventsJsExecResponse struct {
	Created            time.Time `json:"created"`
	EventTrackerId     string    `json:"eventTrackerId,omitempty"`
	ThreadId           string    `json:"threadId"`
	OrgId              string    `json:"orgId"`
	PathKey            string    `json:"pathKey,omitempty"`
	Name               string    `json:"name,omitempty"`
	Description        string    `json:"description,omitempty"`
	Event              string    `json:"event,omitempty"`
	Success            bool      `json:"success"`
	FailedAt           string    `json:"failedAt,omitempty"`
	TotalExecutionTime uint32    `json:"totalExecutionTime"`
	Error              string    `json:"error,omitempty"`
	RetentionDays      uint16    `json:"retentionDays"`
}

// EventsJsExecCursorResult represents the cursor-paginated response for JS Executor events.
type EventsJsExecCursorResult struct {
	// Items contains the list of JS Executor events
	Items []EventsJsExecResponse `json:"items"`

	// NextCursor is the timestamp to use for fetching the next page
	NextCursor *time.Time `json:"nextCursor,omitempty"`

	// PrevCursor is the timestamp to use for fetching the previous page
	PrevCursor *time.Time `json:"prevCursor,omitempty"`

	// HasNext indicates if there are more items after the current page
	HasNext bool `json:"hasNext"`

	// HasPrevious indicates if there are more items before the current page
	HasPrevious bool `json:"hasPrevious"`
}

// JsExecEventExecution represents the execution details from JS Executor.
// This is a nested structure within JsExecEventDTO.
type JsExecEventExecution struct {
	Success            bool   `json:"success"`
	FailedAt           string `json:"failedAt"`
	TotalExecutionTime uint32 `json:"totalExecutionTime"`
	Error              string `json:"error"`
}

// JsExecEventDTO represents the payload received from JS Executor via NATS.
// This is the message structure from the js-executor service with nested Execution.
//
// Field names follow the standardized events_raw pattern:
//   - EventTrackerId: UUID for tracking event across the pipeline (generated by JS-Executor)
//   - ThreadId: Asset UUID identifier (or 'n/a' if not available)
//   - Name: Data source name
//   - Description: Data source description
//   - Event: Standardized payload (JSON as map)
type JsExecEventDTO struct {
	// Created is the event occurrence time (optional, defaults to now)
	Created *time.Time `json:"created"`

	// EventTrackerId is the UUID for tracking event across the pipeline
	EventTrackerId string `json:"eventTrackerId"`

	// ThreadId is the asset UUID identifier (or 'n/a' if not available)
	ThreadId string `json:"threadId" validate:"required"`

	// OrgId is the organization ID for multi-tenant isolation
	OrgId string `json:"orgId"`

	// PathKey is the hierarchical path for multi-tenant range queries
	PathKey string `json:"pathKey"`

	// Name is the data source name (optional)
	Name string `json:"name"`

	// Description is the data source description (optional)
	Description string `json:"description"`

	// Execution contains the script execution details (required)
	Execution JsExecEventExecution `json:"execution" validate:"required"`

	// Event is the standardized payload as JSON map
	Event map[string]interface{} `json:"event"`
}

// JsExecEventFlatDTO represents the flat DTO for mapping to JsExecEvent entity.
// This DTO has the same flat structure as the entity to enable generic mapper usage.
// Use ToFlatDTO() on JsExecEventDTO to convert from nested to flat structure.
//
// Fields match JsExecEvent entity for use with mapper.DtoToEntity[].
type JsExecEventFlatDTO struct {
	// Created is the event occurrence time (optional, defaults to now)
	Created *time.Time `json:"created"`

	// EventTrackerId is the UUID for tracking event across the pipeline
	EventTrackerId string `json:"eventTrackerId"`

	// ThreadId is the asset UUID identifier (or 'n/a' if not available)
	ThreadId string `json:"threadId"`

	// OrgId is the organization ID for multi-tenant isolation
	OrgId string `json:"orgId"`

	// PathKey is the hierarchical path for multi-tenant range queries
	PathKey string `json:"pathKey"`

	// Name is the data source name (optional)
	Name string `json:"name"`

	// Description is the data source description (optional)
	Description string `json:"description"`

	// Event is the standardized payload as JSON map
	Event map[string]interface{} `json:"event"`

	// Success indicates if the script execution was successful
	Success bool `json:"success"`

	// FailedAt indicates which step failed (empty if success)
	FailedAt string `json:"failedAt"`

	// TotalExecutionTime is the execution time in milliseconds
	TotalExecutionTime uint32 `json:"totalExecutionTime"`

	// Error contains the error message if execution failed
	Error string `json:"error"`
}

// ToFlatDTO converts the nested DTO to a flat DTO for entity mapping.
// This enables use of mapper.DtoToEntity[] generic function.
func (d *JsExecEventDTO) ToFlatDTO() *JsExecEventFlatDTO {
	return &JsExecEventFlatDTO{
		Created:            d.Created,
		EventTrackerId:     d.EventTrackerId,
		ThreadId:           d.ThreadId,
		OrgId:              d.OrgId,
		PathKey:            d.PathKey,
		Name:               d.Name,
		Description:        d.Description,
		Event:              d.Event,
		Success:            d.Execution.Success,
		FailedAt:           d.Execution.FailedAt,
		TotalExecutionTime: d.Execution.TotalExecutionTime,
		Error:              d.Execution.Error,
	}
}
