package entities

import (
	"time"
)

/**
 * BusinessRuleEvent represents a business rule execution event stored in ClickHouse.
 * These events are generated by the workflow service for execution tracking.
 *
 * ClickHouse table: events_businessrule
 *
 * Note: Field order matches ClickHouse column order for efficient scanning.
 */
type BusinessRuleEvent struct {
	// Created is the event occurrence time (always UTC)
	Created time.Time `ch:"created"`

	// EventTrackerId is the UUID for tracking event across the pipeline
	EventTrackerId string `ch:"event_tracker_id"`

	// ThreadId is the external correlation identifier
	ThreadId string `ch:"thread_id"`

	// OrgId is the organization identifier for multi-tenancy
	OrgId string `ch:"org_id"`

	// PathKey is the hierarchical path for multi-tenant range queries
	PathKey string `ch:"path_key"`

	// RuleId is the rule template ID
	RuleId string `ch:"rule_id"`

	// BusinessRuleId is the business rule instance ID
	BusinessRuleId string `ch:"business_rule_id"`

	// BusinessRuleName is the business rule name for display
	BusinessRuleName string `ch:"business_rule_name"`

	// BusinessRuleDescription is the business rule description
	BusinessRuleDescription string `ch:"business_rule_description"`

	// Matched indicates if the rule matched (0 or 1)
	Matched uint8 `ch:"matched"`

	// DurationMs is the execution duration in milliseconds
	DurationMs int64 `ch:"duration_ms"`

	// ConditionsEvaluated is the number of conditions evaluated
	ConditionsEvaluated uint16 `ch:"conditions_evaluated"`

	// ConditionsMatched is the number of conditions that matched
	ConditionsMatched uint16 `ch:"conditions_matched"`

	// GroupsEvaluated is the number of groups evaluated
	GroupsEvaluated uint16 `ch:"groups_evaluated"`

	// MaxDepthReached is the maximum depth reached during evaluation
	MaxDepthReached uint16 `ch:"max_depth_reached"`

	// FinalState is the final state as JSON string
	FinalState string `ch:"final_state"`

	// StateChanges is the state changes as JSON string
	StateChanges string `ch:"state_changes"`

	// EvaluationTree is the hierarchical evaluation tree as JSON string
	EvaluationTree string `ch:"evaluation_tree"`

	// ConditionLogs is the condition logs array as JSON string
	ConditionLogs string `ch:"condition_logs"`

	// ActionsToDispatch is the actions to dispatch as JSON string
	ActionsToDispatch string `ch:"actions_to_dispatch"`

	// RetentionDays specifies how long this event should be kept
	RetentionDays uint16 `ch:"retention_days"`
}
