package entities

import (
	"time"
)

/**
 * JsExecEvent represents a JS Executor debug event stored in ClickHouse.
 * These events are generated by the js-executor service for script execution tracking.
 *
 * ClickHouse table: events_jsexecutor
 *
 * Note: Field order matches ClickHouse column order for efficient scanning.
 */
type JsExecEvent struct {
	// Created is the event occurrence time (always UTC)
	Created time.Time `ch:"created"`

	// EventTrackerId is the UUID for tracking event across the pipeline
	EventTrackerId string `ch:"event_tracker_id"`

	// ThreadId is the asset UUID identifier (or 'n/a' if not available)
	ThreadId string `ch:"thread_id"`

	// OrgId is the organization identifier for multi-tenancy
	OrgId string `ch:"org_id"`

	// PathKey is the hierarchical path for multi-tenant range queries
	PathKey string `ch:"path_key"`

	// Name is the data source name (optional)
	Name string `ch:"name"`

	// Description is the data source description (optional)
	Description string `ch:"description"`

	// Event contains the standardized payload as JSON string
	Event string `ch:"event"`

	// Success indicates if the script execution was successful
	Success bool `ch:"success"`

	// FailedAt indicates which step failed (empty if success)
	FailedAt string `ch:"failed_at"`

	// TotalExecutionTime is the execution time in milliseconds
	TotalExecutionTime uint32 `ch:"total_execution_time"`

	// Error contains the error message if execution failed
	Error string `ch:"error"`

	// RetentionDays specifies how long this event should be kept
	RetentionDays uint16 `ch:"retention_days"`
}
