package entities

import (
	"time"
)

/**
 * RouterEvent represents a router execution history event stored in ClickHouse.
 * These events are generated by the router service for route execution tracking.
 *
 * ClickHouse table: events_router
 *
 * Note: Field order matches ClickHouse column order for efficient scanning.
 */
type RouterEvent struct {
	// Created is the event occurrence time (always UTC)
	Created time.Time `ch:"created"`

	// EventTrackerId is the UUID for tracking event across the pipeline
	EventTrackerId string `ch:"event_tracker_id"`

	// ThreadId is the asset identifier used for grouping events
	ThreadId string `ch:"thread_id"`

	// OrgId is the organization identifier for multi-tenancy
	OrgId string `ch:"org_id"`

	// PathKey is the hierarchical path for multi-tenant range queries
	PathKey string `ch:"path_key"`

	// AssetId is the asset that triggered the routing
	AssetId string `ch:"asset_id"`

	// RouterId is the RouteGroup ID
	RouterId string `ch:"router_id"`

	// Name is the RouteGroup name
	Name string `ch:"name"`

	// Description is the RouteGroup description
	Description string `ch:"description"`

	// TotalRouters is the number of routers in the RouteGroup
	TotalRouters uint8 `ch:"total_routers"`

	// MatchedCount is the number of routers that matched conditions
	MatchedCount uint8 `ch:"matched_count"`

	// PublishedCount is the number of routers that published events
	PublishedCount uint8 `ch:"published_count"`

	// Event contains the routers array as JSON string
	Event string `ch:"event"`

	// Success indicates if at least one router was published
	Success uint8 `ch:"success"`

	// Error contains error message if routing failed
	Error string `ch:"error"`

	// RetentionDays specifies how long this event should be kept
	RetentionDays uint16 `ch:"retention_days"`
}
