package entities

import (
	"time"
)

/**
 * TriggerEvent represents a trigger execution event stored in ClickHouse.
 * These events are generated by the triggers service for execution tracking.
 *
 * ClickHouse table: events_trigger
 *
 * Note: Field order matches ClickHouse column order for efficient scanning.
 */
type TriggerEvent struct {
	// Created is the event occurrence time (always UTC)
	Created time.Time `ch:"created"`

	// EventTrackerId is the UUID for tracking event across the pipeline
	EventTrackerId string `ch:"event_tracker_id"`

	// OrgId is the organization identifier for multi-tenancy
	OrgId string `ch:"org_id"`

	// PathKey is the hierarchical path for multi-tenant range queries
	PathKey string `ch:"path_key"`

	// TriggerId is the trigger identifier
	TriggerId string `ch:"trigger_id"`

	// TriggerName is the trigger name for display
	TriggerName string `ch:"trigger_name"`

	// TriggerType is the trigger type (http, mqtt, rabbitmq, nats, websocket, email, teams, slack)
	TriggerType string `ch:"trigger_type"`

	// Category is the trigger category (technical, communication)
	Category string `ch:"category"`

	// Source is the origin of the trigger execution (router)
	Source string `ch:"source"`

	// Success indicates if the trigger executed successfully (0 or 1)
	Success uint8 `ch:"success"`

	// DurationMs is the execution duration in milliseconds
	DurationMs int64 `ch:"duration_ms"`

	// Error is the error message if the trigger failed
	Error string `ch:"error"`

	// RequestData is the resolved config sent to the trigger as JSON string
	RequestData string `ch:"request_data"`

	// ResponseData is the response from the trigger as JSON string
	ResponseData string `ch:"response_data"`

	// RetentionDays specifies how long this event should be kept
	RetentionDays uint16 `ch:"retention_days"`
}
