package entities

import (
	"time"
)

/**
 * WorkflowEvent represents a workflow execution event stored in ClickHouse.
 * These events are generated by the Archiver when executions reach a terminal state
 * (completed, failed, cancelled).
 *
 * ClickHouse table: events_workflow
 *
 * Note: Field order matches ClickHouse column order for efficient scanning.
 */
type WorkflowEvent struct {
	// Created is the execution creation time (always UTC)
	Created time.Time `ch:"created"`

	// Finished is when the execution reached a terminal state (always UTC)
	Finished time.Time `ch:"finished"`

	// ExecutionId is the MongoDB ObjectId (hex string) — unique identifier for this execution
	ExecutionId string `ch:"execution_id"`

	// EventTrackerId is the UUID for tracking event across the pipeline (optional)
	EventTrackerId string `ch:"event_tracker_id"`

	// OrgId is the organization identifier for multi-tenancy
	OrgId string `ch:"org_id"`

	// PathKey is the hierarchical path for multi-tenant range queries
	PathKey string `ch:"path_key"`

	// WorkflowUUID is the unique execution identifier (optional — auto-generated if not provided)
	WorkflowUUID string `ch:"workflow_uuid"`

	// InstanceId is the workflow instance that triggered this execution
	InstanceId string `ch:"instance_id"`

	// DefinitionId is the workflow definition used
	DefinitionId string `ch:"definition_id"`

	// WorkflowName is the workflow name for display (legacy — same as InstanceName)
	WorkflowName string `ch:"workflow_name"`

	// InstanceName is the instance display name
	InstanceName string `ch:"instance_name"`

	// DefinitionName is the definition display name
	DefinitionName string `ch:"definition_name"`

	// Status is the terminal status (completed, failed, cancelled)
	Status string `ch:"status"`

	// Success indicates if the execution completed successfully
	Success bool `ch:"success"`

	// DurationMs is the total execution duration in milliseconds (Finished - Created)
	DurationMs int64 `ch:"duration_ms"`

	// ErrorMessage is the error description or cancel reason (optional)
	ErrorMessage string `ch:"error_message"`

	// ExecutionPath is the DAG execution trail as JSON string
	ExecutionPath string `ch:"execution_path"`

	// NodeOutputs is the map of node outputs as JSON string
	NodeOutputs string `ch:"node_outputs"`

	// ErrorInfo is the full error details as JSON string (optional)
	ErrorInfo string `ch:"error_info"`

	// EventPayload is the trigger payload as JSON string (optional)
	EventPayload string `ch:"event_payload"`

	// TriggerSource indicates what triggered this execution (workflow, subworkflow, http)
	TriggerSource string `ch:"trigger_source"`

	// ParentExecutionId is the parent execution for subworkflows (optional)
	ParentExecutionId string `ch:"parent_execution_id"`

	// Depth is the subworkflow nesting level (0 for root executions)
	Depth uint8 `ch:"depth"`

	// RetentionDays specifies how long this event should be kept
	RetentionDays uint16 `ch:"retention_days"`

	// State is the workflow state variables at completion as JSON string
	State string `ch:"state"`

	// ExternalInputs is the external input values provided at trigger time as JSON string
	ExternalInputs string `ch:"external_inputs"`
}
